# Generated by Django 4.1.3 on 2022-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallresult',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='overallresult',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='overallresult',
            name='status',
        ),
        migrations.AddField(
            model_name='semesterstudentresult',
            name='ca',
            field=models.FloatField(default=0.0, verbose_name='Continuous Assessments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterstudentresult',
            name='fe',
            field=models.FloatField(default=0.0, verbose_name='Final Examination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterstudentresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Passed'), (0, 'Not Passed')], default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Course Name'),
        ),
    ]
