# Generated by Django 4.1.4 on 2022-12-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coursentalevels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseNTALevels',
            new_name='CourseNTALevel',
        ),
    ]
