# Generated by Django 4.1.4 on 2022-12-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_coursentalevels_coursentalevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursentalevel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursentalevel',
            name='nta_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ntalevel', verbose_name='NTA Level'),
        ),
        migrations.AlterField(
            model_name='studentmoduleresult',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')]),
        ),
    ]
