# Generated by Django 4.1.3 on 2022-11-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_semesterstudentresult_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.IntegerField(choices=[(0, 'Enrollment Complete'), (1, 'Enrollment Complete')], verbose_name='Enrolment Status'),
        ),
        migrations.AlterField(
            model_name='semesterstudentresult',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')]),
        ),
    ]
