# Generated by Django 4.1.3 on 2022-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enrollment_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='starting_year',
            field=models.DateField(),
        ),
    ]
