# Generated by Django 4.1.3 on 2022-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enrollment_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.IntegerField(choices=[(0, 'Enrollment InComplete'), (1, 'Enrollment Complete')], verbose_name='Enrolment Status'),
        ),
    ]
