# Generated by Django 4.1.4 on 2022-12-08 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_enrollment_end_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=20, verbose_name='Module Grade')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.module', verbose_name='Module')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='semesterstudentresult',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semesterstudentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ntalevel',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='overallresult',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='ntalevel',
            name='number_of_semesters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overallresult',
            name='class_award',
            field=models.CharField(default='HIGH', max_length=200, verbose_name='Classification Award'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Kelvin', max_length=200, verbose_name='Student First Names'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=200, verbose_name='Student Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Remmy', max_length=200, verbose_name='Student Last Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassModule',
        ),
        migrations.DeleteModel(
            name='SemesterStudentResult',
        ),
        migrations.AddField(
            model_name='studentmoduleresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student', verbose_name='Student'),
        ),
    ]
