# Generated by Django 4.1.4 on 2022-12-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentmoduleresult_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission',
        ),
    ]
